monolog:
  channels: ['deprecation']
  handlers:
    main:
      type: stream
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: debug
      channels: ['!event']
    console:
      type: console
      process_psr_3_messages: false
      channels: ['!event', '!doctrine', '!console']

when@dev:
  monolog:
    handlers:
      main:
        type: rotating_file
        max_files: 10
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        level: debug

when@prod:
  monolog:
    processors:
      psr_log_message: { }
    handlers:
      main:
        type: fingers_crossed
        action_level: error
        handler: nested
        excluded_http_codes: [404, 405]
        buffer_size: 50
      nested:
        type: rotating_file
        max_files: 10
        path: '%kernel.logs_dir%/%kernel.environment%.log'
        formatter: monolog.formatter.json
      deprecation:
        type: rotating_file
        max_files: 10
        path: '%kernel.logs_dir%/deprecation_%kernel.environment%.log'
        channels: [deprecation]