version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: CODE_CHALLENGER
    ports:
      - "8000:8000"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    environment:
      - APP_ENV=dev
    command: php -S 0.0.0.0:8000 -t public
